name: Rebase Pull Requests
author: Guillaume Clochard <guillaume@wuips.com>
description: Use this actions to rebase pull requests

inputs:
  token:
    description: A Github token.
    required: true

  base:
    description: The base branch name or ref to rebase on.
    required: false
    default: 'main'

  label:
    description: Only rebase pull requests with this label
    required: false

  onlyOne:
    description: >
      Only rebase one pull request. Usefull if you have another workflow that
      automatically merge pull requests. "true"|"false"
    required: false
    default: 'false'

  gitUserName:
    description: What to use as git user.name config
    required: false
    default: 'Rebase Action'

  gitUserEmail:
    description: What to use as git user.email config
    required: false
    default: 'rebase@test.com'

runs:
  using: 'node12'
  main: 'lib/main.js'

branding:
  color: 'orange'
  icon: 'git-branch'
