name: Build actions on pull requets

on:
  push:
    branches:
    - '*'
    - '!main'
    - '!release'

jobs:
  build:
    runs-on: ubuntu-18.04

    name: 'Build Javascript actions'

    steps:
      - name: 'Checkout directory'
        uses: actions/checkout@v1

      - name: 'Init Git name'
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "github-workflow@fp51.dev"

      - name: 'Checkout release branch'
        env:
          REF: ${{ github.ref }}
        run: >
          branch=${REF#"refs/heads/"}
          releaseBranch=release-$branch

          if git fetch origin $releaseBranch; then
            echo Release branch origin/$releaseBranch already exists

            git checkout $releaseBranch
          else
            echo Release branch $releaseBranch does not exist

            git checkout -b $releaseBranch origin/$branch
          fi

      - name: 'Merge pull request branch on release branch'
        env:
          REF: ${{ github.ref }}
        run: >
          branch=${REF#"refs/heads/"}

          git merge origin/$branch --strategy-option=theirs --no-ff

      - name: 'Build Javascript actions'
        uses: fp51/actions/build-javascript-actions@487d3feff432e41f139f529f92a611e92c8c7112
        with:
          build_directory: 'lib'

      - name: 'Commit and push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          authenticatedUrl="https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git remote set-url origin $authenticatedUrl

          if [ ! -n "$(git status --porcelain)" ]; then
            echo "Nothing to commit.";
          else
            git add .
            git commit --quiet --message "Built Javascript actions"
          fi

          git push origin HEAD

